name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.xml"
      - "**.ipynb"
      - "Guides/**"
      - "Docs/**"
      - ".vscode/**"
  workflow_dispatch:
    inputs:
      tag:
        required: false
        default: all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

jobs:
  Tests_WinPS5:
    runs-on: windows-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: powershell

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v6

      - name: Install Pester
        run: Install-Module Pester -MinimumVersion 6.0.0 -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Test
        run: |
          $configuration = & ./PesterConfiguration.ps1
          $configuration.Run.Exit = $true
          $configuration.TestResult.Enabled = $true
          $configuration.Output.Verbosity = 'Detailed'
          if('${{ inputs.tag }}' -eq ''){$configuration.Filter.Tag = 'Offline'}
          elseif('${{ inputs.tag }}' -ne 'all'){$configuration.Filter.Tag = '${{ inputs.tag }}'}
          Invoke-Pester -Configuration $configuration

  Tests_PS7:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    defaults:
      run:
        shell: pwsh

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v6

      - name: Install Pester
        run: Install-Module Pester -MinimumVersion 6.0.0 -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Test
        run: |
          $configuration = & ./PesterConfiguration.ps1
          $configuration.Run.Exit = $true
          $configuration.TestResult.Enabled = $true
          $configuration.Output.Verbosity = 'Detailed'
          if('${{ inputs.tag }}' -eq ''){$configuration.Filter.Tag = 'Offline'}
          elseif('${{ inputs.tag }}' -ne 'all'){$configuration.Filter.Tag = '${{ inputs.tag }}'}
          Invoke-Pester -Configuration $configuration
